@Api_HostAddress = http://localhost:5070

GET {{Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST http://localhost:5070/api/player
Content-Type: application/json

{
    "name": "Maria",
    "email": "mariafd@gmail.com",
    "phone": 3223666890,
    "password": "12345678932"
}

###

GET {{Api_HostAddress}}/api/player/
Accept: application/json

###

PUT {{Api_HostAddress}}/api/player/8a14a201-5c77-440c-911c-eee649cb5089
Content-Type: application/json

{
    "playerId": "8a14a201-5c77-440c-911c-eee649cb5089",
    "name": "Juan",
    "email": "juan@gmail.com",
    "phone": "3223666896",
    "isAdmin": true,
    "isActive": true,
    "balance": 200.00
}

###

POST http://localhost:5070/api/game
Content-Type: application/json

{
    "weeknumber": "21",
    "year": "2044",
    "iscomplete": true,
    "prizesum": "123456.25"
}

###

GET {{Api_HostAddress}}/api/game/
Accept: application/json

###

PUT {{Api_HostAddress}}/api/game/1afdf397-a513-4c98-a113-6140f6fede92
Content-Type: application/json

{
    "gameID": "1afdf397-a513-4c98-a113-6140f6fede92",
    "isComplete": true,
    "Winningnumbers": [5, 12, 16],
    "Prizesum": 200.00
}

###

POST http://localhost:5070/api/board
Content-Type: application/json

{
    "playerid": "91f4a3cd-4c3f-437b-8298-5aa6b91321a7",
    "gameid": "1d588464-6d6d-43ac-ad54-d8c815ae32c8",
    "numbers": [5, 12, 19, 28, 36, 42],
    "isautoplay": true
}

###

GET {{Api_HostAddress}}/api/board/
Accept: application/json

###

POST http://localhost:5070/api/winner
Content-Type: application/json

{
    "playerid": "91f4a3cd-4c3f-437b-8298-5aa6b91321a7",
    "gameid": "1d588464-6d6d-43ac-ad54-d8c815ae32c8",
    "boardid": "d0f96b5b-a12f-459d-aaae-ae471d67504b",
    "winningamount": "500.50"
}

###

GET {{Api_HostAddress}}/api/winner/
Accept: application/json

###

POST http://localhost:5070/api/balance
Content-Type: application/json

{
    "playerid": "91f4a3cd-4c3f-437b-8298-5aa6b91321a7",
    "transactiontype": "MobilePay Code",
    "amount": "600",
    "balanceaftertransaction": "650",
    "description": "fersf3242"
}

###
