services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: RataTech
      POSTGRES_PASSWORD: 1127344
      POSTGRES_DB: DeadPigeonsDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build:
      context: ./Server
      dockerfile: DockerFile
    container_name: dotnet_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DbConnectionString: "Host=postgres_db;Port=5432;Database=DeadPigeonsDb;Username=RataTech;Password=1127344"
    depends_on:
      - postgres
    networks:
      - backend
    command: >
      sh -c "dotnet ef database update --project Server/DataAccess &&
             dotnet run --project Server/Api"

volumes:
  pgdata:

networks:
  backend:
