services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: RataTech
      POSTGRES_PASSWORD: 1127344
      POSTGRES_DB: DeadPigeonsDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-scripts:/docker-entrypoint-initdb.d
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: 

