FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

COPY Server/serverSln.sln .
COPY Server/Api/ Api/
COPY Server/Service/ Service/
COPY Server/DataAccess/ DataAccess/
COPY Server/Tests/ Tests/

RUN dotnet restore Api/Api.csproj

COPY . .  
WORKDIR /source/Api
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app .


EXPOSE 8080

ENTRYPOINT ["dotnet", "Api.dll"]
