# crear un tablero
POST http://localhost:5070/api/boards HTTP/1.1
Content-Type: application/json

{
  "selectedNumbers": [1, 2, 3, 4, 5],
  "cost": 20
}

# obtener todos los tableros
GET http://localhost:5070/api/boards HTTP/1.1
